release:
  prerelease: false

builds:
  - binary: sigil
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd 
    goarch:
      - amd64
      - arm64
      - arm
archives:
  - format: binary
# brews:
#   - github:
#       owner: msfidelis
#       name: homebrew-sigil
#     homepage: "https://github.com/msfidelis/sigil/"
#     description: "The Command Line of Doors - Just an "lsof" wrapper for lazy people "